export const APP_CONFIG = {
    NODE_ENV: process.env.NODE_ENV,

    ALCHEMY_API_KEY: process.env.NEXT_PUBLIC_ALCHEMY_API_KEY,
    INFURA_API_KEY: process.env.NEXT_PUBLIC_INFURA_API_KEY,
    ETHERSCAN_API_KEY: process.env.NEXT_PUBLIC_ETHERSCAN_API_KEY
}
