export const APP_CONFIG = {
    NODE_ENV: process.env.NODE_ENV,

    ALCHEMY_API_KEY: process.env.NEXT_PUBLIC_ALCHEMY_API_KEY,
    INFURA_API_KEY: process.env.NEXT_PUBLIC_INFURA_API_KEY,
    ETHERSCAN_API_KEY: process.env.NEXT_PUBLIC_ETHERSCAN_API_KEY,
    POKT_API_KEY: process.env.NEXT_PUBLIC_POKT_API_KEY,

    POAP_CLIENT_ID: process.env.POAP_CLIENT_ID,
    POAP_CLIENT_SECRET: process.env.POAP_CLIENT_SECRET,
    POAP_TEST_EVENT_ID: process.env.POAP_TEST_EVENT_ID,
    POAP_TEST_EVENT_SECRET: process.env.POAP_TEST_EVENT_SECRET
}
